# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v3
          - name: build
            run: |
              python3 -m pip install --upgrade build
              python3 -m build
          - name: Upload a Build Artifact
            uses: actions/upload-artifact@v3.1.1
            with:
              name: build
              path: ./dist
#          - name: build
#            run: |
#              python -m pip install --upgrade pip
#              pip install wheel setuptools scikit-build cffi ninja cmake
#          - name: wheel
#            working-directory: ${{env.GITHUB_WORKSPACE}}
#            run:  |
#              pip install wheel cmake-build-extension auditwheel
#              pip wheel .  --no-deps -w wheelhouse/

#          - name: Upload a Build Artifact
#            uses: actions/upload-artifact@v3.1.1
#            with:
#              name: wheel
#              path: ./wheelhouse/*.whl              
  repair:
     needs: [build]
     runs-on: ubuntu-latest
     container: quay.io/pypa/manylinux_2_24_x86_64
     steps:
         - name: Download dists
           uses: actions/download-artifact@v3.0.1
           with:
             name: build
             path: dist
         - name: wheel   
           working-directory: dist
           run:  |
              mywheel=$(ls *.whl)
              auditwheel repair $mywheel
         - name: Upload a Build Artifact
           uses: actions/upload-artifact@v3.1.1
           with:
            name: dist
            path: ./dist/wheelhouse/*.whl                           
  publish:
      needs: [repair]
      runs-on: ubuntu-latest      
      steps:
          - name: Download a Build Artifact
            uses: actions/download-artifact@v3.0.1
            with:
              name: dist
              path: dist
          - name: Publish package
            uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
            with:
              user: __token__
              password: ${{ secrets.PYPI_API_TOKEN }}
