# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v3
         - name: Build src
           run: |
            python -m pip install --upgrade pip
            pip install wheel setuptools scikit-build cffi ninja cmake
            python setup.py sdist
         - name: Store src
           uses: actions/upload-artifact@v2
           with:
            name: dist
            path: dist/*.tar.gz  
  publish:
      needs: [build]
      runs-on: ubuntu-latest      
      steps:
          - name: Download a Build Artifact
            uses: actions/download-artifact@v3.0.1
            with:
              name: dist
              path: dist
          - name: Publish package
            uses: pypa/gh-action-pypi-publish@release/v1
            with:
              user: __token__
              password: ${{ secrets.PYPI_API_TOKEN }}
